import { prisma } from '@/lib/prisma';
import { shapePublicReviewForApi } from '@/lib/shapePublicReviews';
import { formatAgentTitle, pickAgentAvatar, resolveProfileMediaUrl } from '@/lib/agentProfile';
import { isAgentOrAgencySeller } from '@/lib/sellerDisplay';
import { resolveOfferPrimaryImage } from '@/lib/offers/primaryImage';

export async function loadAgentPublicProfile(userId: number) {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: {
      id: true,
      name: true,
      email: true,
      phone: true,
      image: true,
      role: true,
      planType: true,
      companyName: true,
      createdAt: true,
    },
  });
  if (!user) return null;

  const membership = await prisma.agencyCompanyMember.findUnique({
    where: { userId },
    include: {
      company: {
        select: {
          id: true,
          name: true,
          slug: true,
          address: true,
          website: true,
          logoUrl: true,
          officePhone: true,
          officeEmail: true,
        },
      },
    },
  });

  const isAgent = isAgentOrAgencySeller(user);
  const company = membership?.company ?? null;

  const reviewsRaw = await prisma.review.findMany({
    where: { revieweeId: userId, isAutoGenerated: false },
    include: { reviewer: { select: { id: true, name: true, email: true, image: true } } },
    orderBy: { createdAt: 'desc' },
    take: 50,
  });
  const reviews = reviewsRaw.map((row) => shapePublicReviewForApi(row));

  const offers = await prisma.offer.findMany({
    where: { userId, status: 'ACTIVE' },
    orderBy: { createdAt: 'desc' },
    take: 24,
    select: {
      id: true,
      title: true,
      price: true,
      pricePln: true,
      priceCurrency: true,
      city: true,
      district: true,
      area: true,
      rooms: true,
      images: true,
      transactionType: true,
    },
  });

  const reviewsCount = reviews.length;
  const averageRating =
    reviewsCount > 0
      ? Number((reviews.reduce((s, r) => s + r.rating, 0) / reviewsCount).toFixed(1))
      : null;

  const agentTitle = membership?.agentTitle ?? 'AGENT';
  const profilePhotoUrl = membership?.profilePhotoUrl ?? null;
  const companyLogoUrl = company?.logoUrl ?? null;

  return {
    isAgent,
    agent: {
      id: user.id,
      name: user.name,
      email: user.email,
      phone: user.phone,
      memberSince: user.createdAt.toISOString(),
      role: membership?.role ?? null,
      status: membership?.status ?? null,
      agentTitle,
      titleLabel: formatAgentTitle(agentTitle),
      profilePhotoUrl: resolveProfileMediaUrl(profilePhotoUrl),
      avatarUrl: pickAgentAvatar({
        profilePhotoUrl,
        userImage: user.image,
        companyLogoUrl,
      }),
    },
    company: company
      ? {
          id: company.id,
          name: company.name,
          slug: company.slug,
          address: company.address,
          website: company.website,
          logoUrl: resolveProfileMediaUrl(company.logoUrl),
          officePhone: company.officePhone,
          officeEmail: company.officeEmail,
          firmHref: company.slug ? `/firma/${company.slug}` : null,
        }
      : user.companyName
        ? {
            id: null,
            name: user.companyName,
            slug: null,
            address: null,
            website: null,
            logoUrl: null,
            officePhone: null,
            officeEmail: null,
            firmHref: null,
          }
        : null,
    stats: {
      reviewsCount,
      averageRating,
      activeOffers: offers.length,
    },
    offers: offers.map((o) => ({
      id: o.id,
      title: o.title,
      price: o.price,
      pricePln: o.pricePln,
      priceCurrency: o.priceCurrency,
      city: o.city,
      district: o.district,
      area: o.area,
      rooms: o.rooms,
      transactionType: o.transactionType,
      imageUrl: resolveOfferPrimaryImage(o),
    })),
    reviews,
  };
}
