/**
 * Lekki katalog mapy/listy — bez `description` (HTML bywa setki KB na ofertę).
 * Mobile radar ładuje szczegóły dopiero po wejściu w OfferDetail.
 */
export const MOBILE_OFFER_CATALOG_SELECT = {
  id: true,
  title: true,
  transactionType: true,
  propertyType: true,
  condition: true,
  price: true,
  priceCurrency: true,
  pricePln: true,
  pricePerSqm: true,
  area: true,
  plotArea: true,
  rooms: true,
  floor: true,
  totalFloors: true,
  yearBuilt: true,
  hasBalcony: true,
  hasElevator: true,
  hasStorage: true,
  hasParking: true,
  hasGarden: true,
  isFurnished: true,
  heating: true,
  city: true,
  district: true,
  localityCountryCode: true,
  lat: true,
  lng: true,
  isExactLocation: true,
  images: true,
  status: true,
  expiresAt: true,
  promotedUntil: true,
  listPricePln: true,
  isLegalSafeVerified: true,
  createdAt: true,
  updatedAt: true,
  userId: true,
  user: {
    select: {
      id: true,
      name: true,
      image: true,
      role: true,
      planType: true,
      isPro: true,
    },
  },
} as const;
