import { buildReviewsDistribution } from '@/lib/reviewsDistribution';
import { getBestUserAvatarUrl } from '@/lib/userAvatar';

export type ReviewsModalPayload = {
  averageRating: number;
  totalReviews: number;
  distribution: Record<1 | 2 | 3 | 4 | 5, number>;
  reviews: Array<{
    id: number | string;
    author: string;
    avatar: string;
    avatarUrl?: string | null;
    rating: number;
    date: string;
    text: string;
  }>;
};

export const EMPTY_REVIEWS_MODAL: ReviewsModalPayload = {
  averageRating: 0,
  totalReviews: 0,
  distribution: { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0 },
  reviews: [],
};

type RawReview = {
  id?: number;
  rating?: number | null;
  comment?: string | null;
  createdAt?: string | Date | null;
  isAutoGenerated?: boolean;
  reviewer?: {
    id?: number;
    name?: string | null;
    email?: string | null;
    image?: string | null;
  } | null;
  reviewerId?: number;
};

function formatReviewDate(value: string | Date | null | undefined): string {
  if (!value) return '';
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return '';
  const now = new Date();
  const startToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const startReview = new Date(d.getFullYear(), d.getMonth(), d.getDate());
  const diffDays = Math.round((startToday.getTime() - startReview.getTime()) / 86400000);
  if (diffDays === 0) return 'Dzisiaj';
  if (diffDays === 1) return 'Wczoraj';
  return d.toLocaleDateString('pl-PL', { day: '2-digit', month: 'short', year: 'numeric' });
}

function reviewerLabel(review: RawReview): string {
  const r = review.reviewer;
  if (r?.name?.trim()) return r.name.trim();
  if (r?.email?.trim()) return r.email.split('@')[0];
  if (review.isAutoGenerated) return 'EstateOS';
  return 'Użytkownik';
}

function reviewerAvatarInitial(review: RawReview): string {
  const label = reviewerLabel(review);
  return label.charAt(0).toUpperCase() || '?';
}

/** Ten sam kształt danych co oczekuje `ReviewsModal` — źródło: tabela Review (+ reviewer), jak w aplikacji. */
export function buildReviewsModalPayload(rawReviews: unknown[]): ReviewsModalPayload {
  const list = Array.isArray(rawReviews) ? (rawReviews as RawReview[]) : [];
  const { distribution, totalReviews, averageRating } = buildReviewsDistribution(list);

  const reviews = list.map((r) => ({
    id: r.id ?? `${r.reviewerId}-${r.createdAt}`,
    author: reviewerLabel(r),
    avatar: reviewerAvatarInitial(r),
    avatarUrl: getBestUserAvatarUrl(r.reviewer),
    rating: Math.min(5, Math.max(0, Number(r.rating || 0))),
    date: formatReviewDate(r.createdAt),
    text: String(r.comment || '').trim() || (r.isAutoGenerated ? 'Opinia systemowa po transakcji.' : 'Bez komentarza.'),
  }));

  return { averageRating, totalReviews, distribution, reviews };
}
