/** Etykieta recenzenta na profilu publicznym (imię i nazwisko z konta). */
export function resolvePublicUserName(
  user: { name?: string | null; email?: string | null } | null | undefined,
): string {
  const name = String(user?.name ?? '').trim();
  if (name) return name;
  const email = String(user?.email ?? '').trim();
  if (email) return email.split('@')[0];
  return '';
}

export function shapePublicReviewForApi(review: {
  id: number;
  dealId: number;
  reviewerId: number;
  revieweeId: number;
  rating: number;
  comment: string | null;
  isAutoGenerated?: boolean;
  createdAt: Date;
  reviewer?: { id: number; name: string | null; email: string | null; image?: string | null } | null;
  appointment?: unknown;
}) {
  const reviewerName = resolvePublicUserName(review.reviewer);
  return {
    id: review.id,
    dealId: review.dealId,
    reviewerId: review.reviewerId,
    revieweeId: review.revieweeId,
    rating: review.rating,
    comment: review.comment,
    isAutoGenerated: review.isAutoGenerated ?? false,
    createdAt: review.createdAt,
    reviewerName: reviewerName || null,
    reviewerImage: review.reviewer?.image ?? null,
    appointment: review.appointment ?? null,
  };
}
