export const FALLBACK_DISCOVERY_PULSE = {
  stage: "EXPLORE",
  stageLabel: "Odkrywanie",
  progress: 4,
  confidence: 0,
  contradictionIndex: 0,
  directionLine: "Zacznij oceniać oferty — tu zbudujemy Twój kierunek.",
  suggestion: "Każdy kciuk i każda notatka uczy mózg, czego szukasz.",
  summaryLine: "Za mało swipe’ów do pełnego profilu",
  evidenceHint: null as string | null,
  decisionCount: 0,
  knows: {
    city: null as string | null,
    district: null as string | null,
    budgetPln: null as number | null,
    areaM2: null as number | null,
    transaction: null as "SELL" | "RENT" | "MIXED" | null,
    dislikeReasons: [] as string[],
    lastNotes: [] as string[],
  },
  lastNotes: [] as string[],
  primaryCta: { label: "Oceń pierwsze oferty", href: "/oferty", action: "DISCOVERY" },
  secondaryCta: { label: "Mój kierunek", href: "/moj-kierunek", action: "DIRECTION" },
};
