ALTER TABLE `Deal`
  ADD COLUMN IF NOT EXISTS `finalizedAt` DATETIME(3) NULL;

ALTER TABLE `Review`
  ADD COLUMN IF NOT EXISTS `isAutoGenerated` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS `source` VARCHAR(64) NULL;

CREATE UNIQUE INDEX IF NOT EXISTS `Review_dealId_reviewerId_revieweeId_key`
  ON `Review`(`dealId`, `reviewerId`, `revieweeId`);
