import { Platform, StyleSheet } from 'react-native';

/** Wspólna paleta czatu (Dealroom + Contact). */
export const CHAT_COLORS = {
  background: '#000000',
  surface: '#1C1C1E',
  surfaceElevated: '#2C2C2E',
  primary: '#34C759',
  textBase: '#FFFFFF',
  textMuted: 'rgba(235, 235, 245, 0.6)',
  border: 'rgba(255, 255, 255, 0.1)',
};

export const chatThreadStyles = StyleSheet.create({
  chatScrollView: { flex: 1 },
  chatScrollContent: { padding: 16, paddingBottom: 40 },
  msgWrapper: { marginBottom: 16, maxWidth: '82%' },
  msgMe: { alignSelf: 'flex-end' },
  msgThem: { alignSelf: 'flex-start' },
  msgBubble: { padding: 12, borderRadius: 20 },
  msgBubbleMe: { backgroundColor: CHAT_COLORS.primary, borderBottomRightRadius: 4 },
  msgBubbleThem: { backgroundColor: CHAT_COLORS.surfaceElevated, borderBottomLeftRadius: 4 },
  msgText: { color: CHAT_COLORS.textBase, fontSize: 16, lineHeight: 22 },
  msgTextMe: { color: '#000000', fontWeight: '500' },
  msgFooter: { flexDirection: 'row', alignItems: 'center', marginTop: 4, alignSelf: 'flex-end' },
  msgTime: { color: CHAT_COLORS.textMuted, fontSize: 11, fontWeight: '500' },
  reactionPill: {
    marginTop: -6,
    marginBottom: 2,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: CHAT_COLORS.surfaceElevated,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    alignSelf: 'flex-start',
  },
  reactionPillMe: { alignSelf: 'flex-end' },
  reactionPillThem: { alignSelf: 'flex-start' },
  reactionPillText: { fontSize: 15, lineHeight: 18 },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: CHAT_COLORS.textMuted,
    marginHorizontal: 2,
  },
  inputArea: {
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 34 : 16,
    paddingHorizontal: 12,
  },
  inputRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  textInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    backgroundColor: CHAT_COLORS.surfaceElevated,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    color: CHAT_COLORS.textBase,
    fontSize: 16,
  },
  sendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: CHAT_COLORS.surfaceElevated,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  sendBtnActive: { backgroundColor: CHAT_COLORS.primary },
  loaderCenter: { flex: 1, justifyContent: 'center', alignItems: 'center' },
});
