import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { resolveEliteBadges } from '@/lib/eliteStatus';
import { computePresentationStats } from '@/lib/appointments/presentationFlow';

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
    try {
        const { id } = await params;
        const userIdNum = Number(id);

        if (isNaN(userIdNum)) {
            return NextResponse.json({ error: 'Nieprawidłowe ID' }, { status: 400 });
        }

        const user = await prisma.user.findFirst({
            where: { id: userIdNum },
            select: {
                id: true,
                name: true,
                role: true,
                planType: true,
                isPro: true,
                proExpiresAt: true,
                createdAt: true,
                email: true,
                image: true,
                companyName: true,
                phone: true,
            }
        });

        if (!user) return NextResponse.json({ error: 'Nie znaleziono użytkownika' }, { status: 404 });

        const offers = await prisma.offer.findMany({
            where: { userId: user.id, status: 'ACTIVE' },
            select: { id: true, title: true, price: true, images: true, district: true, city: true, street: true, buildingNumber: true }
        });

        const reviews = await prisma.review.findMany({
            where: { revieweeId: Number(user.id), isAutoGenerated: false },
            include: {
                reviewer: { select: { id: true, name: true, email: true, image: true } },
                appointment: { select: { id: true, proposedDate: true, status: true } },
            },
            orderBy: { createdAt: 'desc' },
            take: 50,
        });

        const appointments = await prisma.appointment.findMany({
            where: {
                status: { in: ['COMPLETED', 'NO_SHOW'] },
                deal: { OR: [{ buyerId: Number(user.id) }, { sellerId: Number(user.id) }] },
            },
            select: { status: true },
        });

        const presentation = computePresentationStats(appointments);
        const badges = resolveEliteBadges(user);

        return NextResponse.json({
            user: {
                id: user.id,
                name: user.name || (user.email ? user.email.split('@')[0] : 'Użytkownik'),
                type: user.planType === 'AGENCY' ? 'agency' : 'private',
                planType: user.planType,
                isPro: user.isPro,
                proExpiresAt: user.proExpiresAt,
                memberSince: user.createdAt,
                image: user.image,
                companyName: user.companyName,
                phone: user.phone,
                badges,
            },
            offers,
            reviews,
            stats: {
                presentations: presentation,
                /** @deprecated use stats.presentations */
                completed: presentation.held,
                excused: 0,
                noShow: presentation.noShow,
                totalAppointments: presentation.scheduled,
            }
        });
    } catch (e) {
        return NextResponse.json({ error: 'Błąd serwera' }, { status: 500 });
    }
}
