-- RadarSearchHistory — historia wyszukiwań radaru (mobile + admin).
CREATE TABLE IF NOT EXISTS `RadarSearchHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `eventType` VARCHAR(64) NOT NULL DEFAULT 'RADAR_SEARCH',
  `transactionType` ENUM('SELL', 'RENT') NULL,
  `propertyType` ENUM('FLAT', 'HOUSE', 'PLOT', 'COMMERCIAL') NULL,
  `city` VARCHAR(128) NULL,
  `districts` JSON NULL,
  `maxPrice` DOUBLE NULL,
  `minArea` DOUBLE NULL,
  `minYear` INT NULL,
  `requireBalcony` TINYINT(1) NOT NULL DEFAULT 0,
  `requireGarden` TINYINT(1) NOT NULL DEFAULT 0,
  `requireElevator` TINYINT(1) NOT NULL DEFAULT 0,
  `requireParking` TINYINT(1) NOT NULL DEFAULT 0,
  `requireFurnished` TINYINT(1) NOT NULL DEFAULT 0,
  `matchCount` INT NULL,
  `lat` DOUBLE NULL,
  `lng` DOUBLE NULL,
  `radius` DOUBLE NULL,
  `queryText` VARCHAR(512) NULL,
  `source` VARCHAR(32) NOT NULL DEFAULT 'mobile',
  `searchedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `RadarSearchHistory_userId_searchedAt_idx` (`userId`, `searchedAt`),
  KEY `RadarSearchHistory_userId_createdAt_idx` (`userId`, `createdAt`),
  CONSTRAINT `RadarSearchHistory_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
