import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { resolveEliteBadges } from '@/lib/eliteStatus';
import { shapePublicReviewForApi } from '@/lib/shapePublicReviews';
import { getUserDisplayAvatar } from '@/lib/agencyCompany';

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
    try {
        const { id } = await params;
        const userIdNum = Number(id);

        if (isNaN(userIdNum)) {
            return NextResponse.json({ error: 'Nieprawidłowe ID' }, { status: 400 });
        }

        // 1. Pobieranie użytkownika (User.id to Int)
        const user = await prisma.user.findFirst({
            where: { id: userIdNum },
            select: {
                id: true,
                name: true,
                role: true,
                planType: true,
                isPro: true,
                proExpiresAt: true,
                createdAt: true,
                email: true,
                image: true,
                companyName: true,
                companyAddress: true,
                companyWebsite: true,
                companyLogoUrl: true,
                officePhone: true,
                officeEmail: true,
                phone: true,
            }
        });

        if (!user) return NextResponse.json({ error: 'Nie znaleziono użytkownika' }, { status: 404 });

        // 2. Pobieranie ofert (Offer.userId to Int)
        const offers = await prisma.offer.findMany({
            where: { userId: user.id, status: { in: ['ACTIVE', 'PENDING'] } },
            orderBy: { createdAt: 'desc' },
            select: { id: true, title: true, price: true, status: true, images: true, district: true, city: true, street: true, buildingNumber: true }
        });

        // 3. Pobieranie opinii
        const reviewsRaw = await prisma.review.findMany({
            where: { revieweeId: Number(user.id), isAutoGenerated: false },
            include: {
                reviewer: { select: { id: true, name: true, email: true, image: true } },
            },
            orderBy: { createdAt: 'desc' },
            take: 50,
        });
        const reviews = reviewsRaw.map((row) => shapePublicReviewForApi(row));

        // 4. Pobieranie statystyk
        const appointments = await prisma.appointment.findMany({
            where: { deal: { OR: [{ buyerId: Number(user.id) }, { sellerId: Number(user.id) }] } },
            select: { status: true }
        });

        const badges = resolveEliteBadges(user);
        const displayImage = await getUserDisplayAvatar(userIdNum);

        return NextResponse.json({
            user: {
                id: user.id,
                name: user.name || (user.email ? user.email.split('@')[0] : 'Użytkownik'),
                type: user.planType === 'AGENCY' ? 'agency' : 'private',
                planType: user.planType,
                isPro: user.isPro,
                proExpiresAt: user.proExpiresAt,
                memberSince: user.createdAt,
                image: displayImage,
                avatar: displayImage,
                avatarUrl: displayImage,
                companyName: user.companyName,
                companyAddress: user.companyAddress,
                companyWebsite: user.companyWebsite,
                companyLogoUrl: user.companyLogoUrl,
                officePhone: user.officePhone,
                officeEmail: user.officeEmail,
                phone: user.phone,
                badges,
            },
            offers,
            reviews,
            stats: {
                totalAppointments: appointments.length,
                completed: appointments.filter(a => a.status === 'ACCEPTED').length,
                excused: appointments.filter(a => a.status === 'DECLINED').length,
                noShow: 0
            }
        });
    } catch (e) {
        return NextResponse.json({ error: 'Błąd serwera' }, { status: 500 });
    }
}
